server:
  port: 8081
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/aoye?useSSL=false
    username: root
    password: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
#  servlet:
#    multipart:
#      max-file-size: 300MB
#      max-request-size: 300MB
#      enabled: true

#  rabbitmq:
#    host: 111.230.104.64
#    username: guest
#    password: guest
#    virtual-host: /leyou
#    templates:
#      retry:
#        enabled: true
#        initial-interval: 10000ms
#        max-interval: 300000ms
#        multiplier: 2
#      exchange: ly.item.exchange
#    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true # 返回eureka的是ip，而不是主机名
    ip-address: 127.0.0.1 # 设置返回的ip是啥
    instance-id: ${spring.application.name}:${server.port}
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#主键秘钥
ay:
  worker:
    workerId: 1   #机器编号 上线应改为实际编号
    datacenterId: 1 #
#文件上传位置，上线时改为实际位置
installersPath: D:\installers
#上传成功图片url
successImgUrl: http://192.168.0.118:10010/api/product/success.png





